// swift-tools-version:5.3

// This file was autogenerated, do not modify

import PackageDescription

let package = Package(
    name: "EpaySDK",
    defaultLocalization: "ru",
    platforms: [
        .iOS(.v12)
    ],
    products: [
        .library(
            name: "EpaySDK",
            targets: ["EpaySDK"]
        ),
    ],
    dependencies: [
        .package(
            url: "https://github.com/getbouncer/cardscan-ios.git", 
            from: "2.1.2"
        )
    ],
    targets: [
        .target(
            name: "EpaySDK",
            dependencies: [.product(name: "CardScan", package: "cardscan-ios")],
            resources: [
                .process("Resources")
            ]
        )
    ]
)